# Generated by Django 5.1.3 on 2024-12-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.CharField(choices=[('up', 'up'), ('down', 'down')], max_length=4),
        ),
    ]
